class Block:
    """Minecraft PI block description. Can be sent to Minecraft.setBlock/s"""
    def __init__(self, id, data=0):
        self.id = id
        self.data = data

    def __cmp__(self, rhs):
        return hash(self) - hash(rhs)

    def __hash__(self):
        return (self.id << 8) + self.data

    def withData(self, data):
        return Block(self.id, data)

    def __iter__(self):
        """Allows a Block to be sent whenever id [and data] is needed"""
        return iter((self.id, self.data))

    def __repr__(self):
        return "Block(%d, %d)"%(self.id, self.data)

AIR                 = Block(0)
STONE               = Block(1)
GRASS               = Block(2)
DIRT                = Block(3)
COBBLESTONE         = Block(4)
WOOD_PLANKS         = Block(5)
SAPLING             = Block(6)
BEDROCK             = Block(7)
WATER_FLOWING       = Block(8)
WATER               = WATER_FLOWING
WATER_STATIONARY    = Block(9)
LAVA_FLOWING        = Block(10)
LAVA                = LAVA_FLOWING
LAVA_STATIONARY     = Block(11)
SAND                = Block(12)
GRAVEL              = Block(13)
GOLD_ORE            = Block(14)
IRON_ORE            = Block(15)
COAL_ORE            = Block(16)
WOOD                = Block(17)
LEAVES              = Block(18)
SPONGE              = Block(19)
GLASS               = Block(20)
LAPIS_LAZULI_ORE    = Block(21)
LAPIS_LAZULI_BLOCK  = Block(22)
DISPENSER           = Block(23)
SANDSTONE           = Block(24)
NOTE_BLOCK          = Block(25)
BED                 = Block(26)
POWERED_RAIL        = Block(27)
DETECTOR_RAIL       = Block(28)
STICKY_PISTON       = Block(29)
COBWEB              = Block(30)
GRASS_TALL          = Block(31)
PISTON              = Block(33)
WOOL                = Block(35)
FLOWER_YELLOW       = Block(37)
FLOWER_CYAN         = Block(38)
MUSHROOM_BROWN      = Block(39)
MUSHROOM_RED        = Block(40)
GOLD_BLOCK          = Block(41)
IRON_BLOCK          = Block(42)
STONE_SLAB_DOUBLE   = Block(43)
STONE_SLAB          = Block(44)
BRICK_BLOCK         = Block(45)
TNT                 = Block(46)
BOOKSHELF           = Block(47)
MOSS_STONE          = Block(48)
OBSIDIAN            = Block(49)
TORCH               = Block(50)
FIRE                = Block(51)
MONSTER_SPAWNER     = Block(52)
STAIRS_WOOD         = Block(53)
CHEST               = Block(54)
DIAMOND_ORE         = Block(56)
DIAMOND_BLOCK       = Block(57)
CRAFTING_TABLE      = Block(58)
FARMLAND            = Block(60)
FURNACE_INACTIVE    = Block(61)
FURNACE_ACTIVE      = Block(62)
STANDING_SIGN_BLOCK = Block(63)
DOOR_WOOD           = Block(64)
LADDER              = Block(65)
RAIL                = Block(66)
STAIRS_COBBLESTONE  = Block(67)
LEVER               = Block(69)
STONE_PRESSURE_PLATE= Block(70)
DOOR_IRON           = Block(71)
REDSTONE_ORE        = Block(73)
REDSTONE_TORCH      = Block(76)
SNOW                = Block(78)
ICE                 = Block(79)
SNOW_BLOCK          = Block(80)
CACTUS              = Block(81)
CLAY                = Block(82)
SUGAR_CANE          = Block(83)
FENCE               = Block(85)
PUMPKIN             = Block(86)
NETHERRACK          = Block(87)
SOUL_SAND           = Block(88)
GLOWSTONE_BLOCK     = Block(89)
JACK                = Block(91)
STAINED_GLASS       = Block(95)
STONE_BRICK         = Block(98)
GLASS_PANE          = Block(102)
MELON               = Block(103)
FENCE_GATE          = Block(107)
EMERALD_ORE         = Block(129)
EMERALD_BLOCK       = Block(133)
BEACON              = Block(138)
COBBLESTONE_WALL    = Block(139)
REDSTONE_BLOCK      = Block(152)
HOPPER              = Block(154)
QUARTZ_BLOCK        = Block(155)
ACTIVATOR_RAIL      = Block(157)
DROPPER             = Block(158)
STAINED_GLASS_PANE  = Block(160)
SLIME_BLOCK         = Block(165)
BARRIER             = Block(166)
PRISMARINE          = Block(168)
SEA_LANTERN         = Block(169)
HAY_BALE            = Block(170)
CARPET              = Block(171)
COAL_BLOCK          = Block(173)
MAGMA_BLOCK         = Block(213)
GLOWING_OBSIDIAN    = Block(246)
NETHER_REACTOR_CORE = Block(247)